services:
  web:
    build:
      context: ../..
      dockerfile: docker/production/Dockerfile.node
    image: ordo-1962:local
    restart: unless-stopped
    container_name: ordo-1962
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - proxy
      - ordo-network
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
      MONGO_INITDB_HOST:
      MONGO_INITDB_PORT:
  mongo:
    build:
      context: ../..
      dockerfile: docker/production/Dockerfile.mongo
    container_name: ordo-mongo
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mongo-data:/data/db
    networks:
      - ordo-network
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
volumes:
  mongo-data:
networks:
  ordo-network:
    name: ordo-network
  proxy:
    external: true
    name: proxy